// AUTO-GENERATED by scripts/art/npcs.py — do not edit by hand.
// 3D festival NPC sheet: per-frame artwork bounds; frame = row * 6 + pose (see npcs.ts).
import type { SheetMeta } from './spriteMeta.generated';

/** The rendered NPC sheet (atlas 'npcs3d', feet registered like the heroes), or null for the 2D sheet. */
export const NPC_SHEET: SheetMeta | null = /*DATA*/null/*DATA*/;
