"""The board cast (host, Star Keeper, shopkeepers, helper) as roster characters.

    python scripts/art/cast_sheet.py

The NPC atlas 'npcs3d' keeps its layout (frame = row * 6 + pose, see src/game/data/npcs.ts), but
each row is now a roster character, composed from that hero's rendered sheet: every NPC pose picks
the closest hero animation frame. Writes public/assets/atlases/npcs3d.webp + .json and
src/game/data/npcSprites.generated.ts (per-frame artwork bounds from the hero metadata). Run
`python scripts/build-lite.py --atlas npcs3d` afterwards for the half-size copy.
"""
from __future__ import annotations

import json
import os

from PIL import Image

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
ATLASES = os.path.join(ROOT, 'public', 'assets', 'atlases')

# NPC row -> (hero, [(npc pose, hero animation, frame in it)]), in the pose order of npcs.ts.
CAST = [
    ('spongebob', [('idle', 'idle', 0), ('wave', 'wave', 2), ('welcome', 'celebrate', 1), ('point', 'dial', 3), ('flag', 'victory', 1), ('cheer', 'celebrate', 2)]),
    ('ironman', [('idle', 'idle', 0), ('tool', 'dial', 1), ('laugh', 'celebrate', 3), ('idea', 'surprised', 1), ('gadget', 'coins', 2), ('surprised', 'surprised', 0)]),
    ('homer', [('idle', 'idle', 0), ('wave', 'wave', 2), ('gift', 'coins', 3), ('point', 'dial', 3), ('coin', 'coins', 1), ('happy', 'celebrate', 4)]),
    ('sonic', [('idle', 'idle', 0), ('happy', 'celebrate', 4), ('laugh', 'celebrate', 3), ('alert', 'surprised', 2), ('apple', 'coins', 2), ('surprised', 'surprised', 0)]),
    ('nami', [('idle', 'idle', 0), ('happy', 'celebrate', 4), ('gift', 'coins', 3), ('cheer', 'celebrate', 2), ('surprised', 'surprised', 0), ('star', 'victory', 3)]),
]


def hero_data() -> dict:
    s = open(os.path.join(ROOT, 'src', 'game', 'data', 'heroSprites.generated.ts')).read()
    d, _ = json.JSONDecoder().raw_decode(s[s.index('/*DATA*/') + len('/*DATA*/'):])
    return d


def main() -> None:
    data = hero_data()
    crops: list[tuple[Image.Image, dict, dict]] = []
    for hero, poses in CAST:
        sheet = Image.open(os.path.join(ATLASES, f'hero_{hero}.webp')).convert('RGBA')
        js = json.load(open(os.path.join(ATLASES, f'hero_{hero}.json')))
        meta = data['meta'][f'hero_{hero}']
        for _pose, anim, k in poses:
            idx = data['anims'][hero][anim]['frames'][k]
            f = js['frames'][str(idx)]
            assert not f.get('rotated'), 'rotated frames are not supported'
            fr = f['frame']
            crops.append((sheet.crop((fr['x'], fr['y'], fr['x'] + fr['w'], fr['y'] + fr['h'])), f, meta['frames'][idx]))
    # Shelf-pack the trimmed frames into a 2048-wide sheet.
    W, gap = 2048, 2
    x = y = shelf = 0
    places = []
    for im, _f, _m in crops:
        if x + im.width > W:
            x, y, shelf = 0, y + shelf + gap, 0
        places.append((x, y))
        x += im.width + gap
        shelf = max(shelf, im.height)
    H = 1 << (y + shelf - 1).bit_length()
    out = Image.new('RGBA', (W, H), (0, 0, 0, 0))
    frames = {}
    for i, ((im, f, _m), (px, py)) in enumerate(zip(crops, places)):
        out.alpha_composite(im, (px, py))
        frames[str(i)] = {**f, 'frame': {'x': px, 'y': py, 'w': im.width, 'h': im.height}}
    out.save(os.path.join(ATLASES, 'npcs3d.webp'), 'WEBP', quality=90, method=6)
    json.dump({'frames': frames, 'meta': {'app': 'scripts/art/cast_sheet.py', 'image': 'npcs3d.webp', 'format': 'RGBA8888', 'size': {'w': W, 'h': H}, 'scale': '1'}},
              open(os.path.join(ATLASES, 'npcs3d.json'), 'w'), separators=(',', ':'))
    first = data['meta'][f'hero_{CAST[0][0]}']
    sheet_meta = {'pad': first.get('pad', 80), 'anchor': first.get('anchor', 'feet'), 'frames': [m for _im, _f, m in crops]}
    ts = (
        '// AUTO-GENERATED by scripts/art/cast_sheet.py — do not edit by hand.\n'
        '// The board cast sheet (roster characters): per-frame artwork bounds; frame = row * 6 + pose (see npcs.ts).\n'
        "import type { SheetMeta } from './spriteMeta.generated';\n\n"
        "/** The rendered cast sheet (atlas 'npcs3d', feet registered like the heroes), or null for the 2D sheet. */\n"
        f'export const NPC_SHEET: SheetMeta | null = /*DATA*/{json.dumps(sheet_meta, separators=(",", ":"))}/*DATA*/;\n'
    )
    open(os.path.join(ROOT, 'src', 'game', 'data', 'npcSprites.generated.ts'), 'w').write(ts)
    print('npcs3d', out.size, len(frames), 'frames')


if __name__ == '__main__':
    main()
