"""Render the five festival NPCs as one 3D sprite sheet in the heroes' look (see characters.py).

    .artenv/bin/python scripts/art/npcs.py [--npc ora,wrench] [--poses idle,wave] [--preview]
                                            [--samples 40] [--pack-only] [--out DIR]

Each NPC lives in scripts/art/npc_<id>.py: MODEL (a char_models.Hero subclass) and POSES, a dict
of the six poses named in POSE_NAMES (the order of src/game/data/npcs.ts). They are rendered with
the heroes' camera and key light and the same fixed registration (feet at characters.FEET), then
packed into public/assets/atlases/npcs3d.webp/.json (frame = row * 6 + pose) plus
src/game/data/npcSprites.generated.ts (per-frame artwork bounds for the game).
"""
from __future__ import annotations

import argparse
import json
import math
import os
import sys
import time

sys.path.insert(0, os.path.dirname(__file__))
import characters as C  # noqa: E402  (camera, lighting, posing and packing helpers)
import lib  # noqa: E402

import numpy as np  # noqa: E402
from PIL import Image  # noqa: E402

from char_models import Mats  # noqa: E402

p = argparse.ArgumentParser()
p.add_argument('--npc', default='ora,wrench,pipper,mimi,packsprout')
p.add_argument('--poses', default='')
p.add_argument('--preview', action='store_true')
p.add_argument('--samples', type=int, default=40)
p.add_argument('--ss', type=float, default=2.0, help='supersampling factor')
p.add_argument('--pack-only', action='store_true')
p.add_argument('--out', default='')
A = p.parse_args(sys.argv[sys.argv.index('--') + 1:] if '--' in sys.argv else sys.argv[1:])

# atlas rows and pose columns, as listed in src/game/data/npcs.ts
POSE_NAMES = {
    'ora': ['idle', 'wave', 'welcome', 'point', 'flag', 'cheer'],
    'wrench': ['idle', 'tool', 'laugh', 'idea', 'gadget', 'surprised'],
    'pipper': ['idle', 'wave', 'gift', 'point', 'coin', 'happy'],
    'mimi': ['idle', 'happy', 'laugh', 'alert', 'apple', 'surprised'],
    'packsprout': ['idle', 'happy', 'gift', 'cheer', 'surprised', 'star'],
}
ORDER = list(POSE_NAMES)
KEY = 'npcs3d'
OUT = A.out or os.path.join(lib.ROOT, 'art-out', 'npcs')
GEN_TS = os.path.join(lib.ROOT, 'src', 'game', 'data', 'npcSprites.generated.ts')


def load(npc: str):
    mod = __import__(f'npc_{npc}')
    missing = [n for n in POSE_NAMES[npc] if n not in mod.POSES]
    if missing:
        raise SystemExit(f'npc_{npc}.py is missing poses: {missing}')
    return mod.MODEL, mod.POSES


def pack():
    images, solids, trims = [], [], []
    for npc in ORDER:
        for name in POSE_NAMES[npc]:
            path = os.path.join(OUT, npc, f'{name}.png')
            if not os.path.exists(path):
                raise SystemExit(f'missing frame {path}: render every NPC before packing')
            im = C.load_frame(path)
            a = np.asarray(im.getchannel('A'))
            ys, xs = np.nonzero(a >= C.ALPHA_SOLID)
            solids.append([int(xs.min()), int(ys.min()), int(xs.max() - xs.min() + 1), int(ys.max() - ys.min() + 1)] if len(xs) else [0, 0, 1, 1])
            bbox = im.getchannel('A').point(lambda v: 255 if v > 6 else 0).getbbox() or (0, 0, 1, 1)
            images.append(im.crop(bbox))
            trims.append(bbox)
    # power-of-two sheet (the game mipmaps its atlases): 2048 wide, or 4096 wide when that is smaller
    W = H = pos = None
    for width in (2048, 4096):
        p_, height = C.shelf_pack([im.size for im in images], width)
        h_ = 1 << max(0, int(math.ceil(math.log2(max(1, height)))))
        if W is None or width * h_ < W * H:
            W, H, pos = width, h_, p_
    atlas = Image.new('RGBA', (W, H), (0, 0, 0, 0))
    frames = {}
    for k, (im, (x, y), bb) in enumerate(zip(images, pos, trims)):
        atlas.paste(im, (x, y))
        frames[str(k)] = {
            'frame': {'x': x, 'y': y, 'w': im.width, 'h': im.height}, 'rotated': False, 'trimmed': True,
            'spriteSourceSize': {'x': bb[0], 'y': bb[1], 'w': im.width, 'h': im.height}, 'sourceSize': {'w': C.FRAME, 'h': C.FRAME},
        }
    atlas.save(os.path.join(C.ATLAS_DIR, KEY + '.webp'), 'WEBP', quality=92, method=6)
    with open(os.path.join(C.ATLAS_DIR, KEY + '.json'), 'w') as fh:
        json.dump({'frames': frames, 'meta': {'app': 'gleamtrail/scripts/art/npcs.py', 'image': KEY + '.webp', 'format': 'RGBA8888',
                                              'size': {'w': W, 'h': H}, 'scale': '1'}}, fh)
    meta = {'pad': 80, 'anchor': 'feet', 'frames': [{'w': C.FRAME, 'h': C.FRAME, 'solid': s_} for s_ in solids]}
    ts = (
        '// AUTO-GENERATED by scripts/art/npcs.py — do not edit by hand.\n'
        '// 3D festival NPC sheet: per-frame artwork bounds; frame = row * 6 + pose (see npcs.ts).\n'
        "import type { SheetMeta } from './spriteMeta.generated';\n\n"
        f'/** The rendered NPC sheet (atlas \'{KEY}\', feet registered like the heroes), or null for the 2D sheet. */\n'
        f'export const NPC_SHEET: SheetMeta | null = /*DATA*/{json.dumps(meta, separators=(",", ":"))}/*DATA*/;\n'
    )
    with open(GEN_TS, 'w') as fh:
        fh.write(ts)
    print('packed', KEY, len(images), 'frames', f'{W}x{H}', flush=True)


def main():
    if A.pack_only:
        pack()
        return
    npcs = [n for n in A.npc.split(',') if n in POSE_NAMES]
    os.makedirs(OUT, exist_ok=True)
    C.setup_scene(16 if A.preview else A.samples, 1.0 if A.preview else A.ss)
    mats = Mats()
    for npc in npcs:
        model, poses = load(npc)
        figure = model(mats)
        os.makedirs(os.path.join(OUT, npc), exist_ok=True)
        for name in POSE_NAMES[npc]:
            if A.poses and name not in A.poses.split(','):
                continue
            path = os.path.join(OUT, npc, f'{name}.png')
            t0 = time.time()
            C.render_frame(figure, poses[name], path)
            print(f'{npc} {name} {time.time() - t0:.1f}s', flush=True)
    if not A.preview and not A.poses and not A.out and set(npcs) == set(ORDER):
        pack()


if __name__ == '__main__':
    main()
