import { describe, expect, it } from 'vitest';
import { CHARACTER_ANIMATIONS } from '../../src/game/characters/CharacterAnimations';
import { CHARACTER_IDS, CHARACTERS } from '../../src/game/data/characters';
import { HERO_DATA } from '../../src/game/data/heroSprites.generated';

// The 3D hero sheets are generated by scripts/art/characters.py; these checks catch a stale or
// partial pack (an animation pointing past the atlas, a hero missing its anchor points).
const rendered = CHARACTER_IDS.filter((id) => HERO_DATA.meta[`hero_${id}`]);

const ATLASES = import.meta.glob<{ frames: Record<string, unknown> }>('../../public/assets/atlases/hero_*.json', { eager: true, import: 'default' });

function atlasFrames(key: string): Record<string, unknown> {
  return ATLASES[`../../public/assets/atlases/${key}.json`]?.frames ?? {};
}

describe('3D hero sprite sheets', () => {
  it('use the rendered atlas for every hero that has one', () => {
    for (const id of rendered) expect(CHARACTERS[id].atlas).toBe(`hero_${id}`);
  });

  it.each(rendered)('%s: every animation frame exists in the atlas', (id) => {
    const frames = atlasFrames(`hero_${id}`);
    const meta = HERO_DATA.meta[`hero_${id}`];
    expect(Object.keys(frames)).toHaveLength(meta.frames.length);
    for (const [name, anim] of Object.entries(CHARACTER_ANIMATIONS[id])) {
      expect(anim.frames.length, name).toBeGreaterThan(0);
      for (const f of anim.frames) expect(frames[String(f)], `${name} frame ${f}`).toBeDefined();
    }
  });

  it.each(rendered)('%s: has the same animation set as the other heroes and its anchor points', (id) => {
    expect(Object.keys(CHARACTER_ANIMATIONS[id]).sort()).toEqual(Object.keys(CHARACTER_ANIMATIONS[rendered[0]]).sort());
    const pts = HERO_DATA.points[id];
    for (const k of ['carry', 'pull', 'face'] as const) {
      expect(pts[k], k).toHaveLength(2);
      // above the feet and within the frame
      expect(pts[k][1], k).toBeLessThan(0);
      expect(Math.abs(pts[k][0]), k).toBeLessThan(194);
    }
  });
});
